In [2]:
import numpy as np

In [17]:
a=np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
a=np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [27]:
a.size




15

In [26]:
a.ndim


2

In [25]:
a.dtype


dtype('int32')

In [30]:
list_b =[1, 2, 3, 4, 5, 6, 7, 8, 9]
b= np.array(list_b).reshape(3,3)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
b=np.array([(1.5,2,3),(4,5,6)])
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [37]:
c=np.array( [ [1,2],[3,4]], dtype=complex)
print(c)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [39]:
zeros=np.zeros( (3,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [42]:
ones=np.ones( (2,3,4), dtype=np.int16)
print(ones)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [41]:
cd=np.arange(0,2,0.3)

In [45]:
#np.linespace(0, 2, 9)

In [49]:
a =np.array([ 20,30,40,50])
print(a)


[20 30 40 50]


In [50]:
b=np.arange(4)
print(b)

[0 1 2 3]


In [51]:
print(c)

[20 29 38 47]


In [54]:
b**2

array([0, 1, 4, 9])

In [53]:
b**2
10*np.sin(a)
a<35

array([ True,  True, False, False])

In [59]:
A=np.array([[1,1],[0,1]])
B=np.array([[2,0],[3,4]])
Prod1=A@B

In [58]:
prod2 = A .dot(B)

In [60]:
print(prod2)

[[5 4]
 [3 4]]


In [61]:
a=np.ones((2,3),dtype=int)
b=np.random.random((2,3))
a *= 3
b += a

In [62]:
a *= 3
print(a)

[[9 9 9]
 [9 9 9]]


In [63]:
b += a
print(b)

[[12.08263923 12.30142521 12.60375572]
 [12.05876475 12.06832845 12.71206547]]


In [64]:
a=np.random.random((2,3))

In [65]:
print(a)

[[0.29359636 0.83453215 0.83644678]
 [0.65314512 0.28601556 0.82821024]]


In [66]:
a.sum()

3.731946197414037

In [67]:
a.min()

0.28601555766482145

In [68]:
a.max()

0.836446775931991

In [72]:
print(b)

[[12.08263923 12.30142521 12.60375572]
 [12.05876475 12.06832845 12.71206547]]


In [70]:
b[0:5, 1]


array([12.30142521, 12.06832845])

In [73]:
b[ : ,1]

array([12.30142521, 12.06832845])

In [74]:
b[1:3,  :]

array([[12.05876475, 12.06832845, 12.71206547]])

stacking array


In [79]:
a=np.floor(10*np.random.random((2,2)))
print(a)

[[3. 4.]
 [1. 9.]]


In [78]:
b=np.floor(10*np.random.random((2,2)))
print(b)

[[7. 8.]
 [8. 1.]]


In [77]:
np.vstack((a,b))

array([[6., 3.],
       [9., 1.],
       [0., 0.],
       [5., 3.]])

In [80]:
np.hstack((a,b))

array([[3., 4., 7., 8.],
       [1., 9., 8., 1.]])

In [81]:
a = np.floor(10*np.random.random((2,12)))

In [82]:
np.hsplit(a,3)

[array([[6., 3., 4., 6.],
        [1., 1., 6., 1.]]),
 array([[0., 1., 4., 6.],
        [0., 0., 4., 0.]]),
 array([[5., 6., 5., 1.],
        [7., 8., 7., 4.]])]

In [83]:
np.hsplit(a,(3,4))

[array([[6., 3., 4.],
        [1., 1., 6.]]),
 array([[6.],
        [1.]]),
 array([[0., 1., 4., 6., 5., 6., 5., 1.],
        [0., 0., 4., 0., 7., 8., 7., 4.]])]